export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Routines } from './Routines';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as Activities } from './Activities';
export { default as NewActivity } from './NewActivity';
export { default as NewRoutine } from './NewRoutine';
